server:
  port:
    4004

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - path=/api/patients/**
          filters:
            -strip-prefix=1

        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - path=/api-docs/patients
          filters:
            - rewrite-path=/api-docs/patients,v3/api-docs

          ## REST CLIENT --> http://localhost:4004/api/patients
          ## API GATEWAY --> http://patient-service:4000/patients <-- Docker Container Name

          ## REST CLIENT --> http://localhost:4004/api-docs/patients
          ## API GATEWAY --> http://patient-service:4000/v3/api-docs
