### POST request to add a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "John Smith",
  "email" : "test@example.com",
  "address": "101 Easy Street",
  "dateOfBirth": "1993-01-01",
  "registeredDate": "2025-12-24"
}

