### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "Jon Jones",
  "email" : "johnjones@gmail.com",
  "address": "8808 Lavender Lace Ct Ne",
  "dateOfBirth": "1987-07-19"
}

